// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Salt struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	SaltValue string       `json:"salt_value"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Status    sql.NullString `json:"status"`
}

type UserCredential struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.NullUUID  `json:"user_id"`
	CredentialType  string         `json:"credential_type"`
	CredentialValue sql.NullString `json:"credential_value"`
	LastUsed        sql.NullTime   `json:"last_used"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}
