services:
  api-gateway:
  
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8080/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    ports:
      - "8080:8080"          # Expose the application on port 8080      docker swarm init
    

  user-service:
    build: 
      context: ./user-service/
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./user-service/
          target: /app
        - action: rebuild
          path: ./user-service/



    networks:
      - app-network


networks:
  app-network:       # Enable service discovery with overlay network
