version: '3.8'

services:
  api-gateway:
  
    build: ./api-gateway/
    networks:
      - app-network
    ports:
      - "8080:8080"          # Expose the application on port 8080      docker swarm init
    

  user-service:
    build: ./user-service/
    networks:
      - app-network


networks:
  app-network:       # Enable service discovery with overlay network
