// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: salt.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSalt = `-- name: CreateSalt :one
INSERT INTO salts (user_id, salt_value)
VALUES ($1, $2)
RETURNING id
`

type CreateSaltParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SaltValue string    `json:"salt_value"`
}

func (q *Queries) CreateSalt(ctx context.Context, arg CreateSaltParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSalt, arg.UserID, arg.SaltValue)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
